language: objective-c
before_install:
  - sudo easy_install cpp-coveralls
script:
  - xctool -scheme libPhoneNumber test ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - ./script/coveralls.sh
